apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: mongodb
  name: mongo
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: mongodb
  name: mongo-pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: mongo-pod-reader-binding
  namespace: mongodb
roleRef:
  kind: Role
  name: mongo-pod-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: mongo
  namespace: mongodb