apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: project-name
  name: datadir-service-name-mongodb-0
  labels:
    ordinal: "0"
    projectName: "project-name"
    serviceName: "service-name"
    dbType: "mongodb"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      capacity: "1Gi"
      ordinal: "0"
      projectName: "project-name"
      serviceName: "service-name"
      dbType: "mongodb"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: project-name
  name: datadir-service-name-mongodb-1
  labels:
    ordinal: "1"
    projectName: "project-name"
    serviceName: "service-name"
    dbType: "mongodb"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      capacity: "1Gi"
      ordinal: "1"
      projectName: "project-name"
      serviceName: "service-name"
      dbType: "mongodb"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: project-name
  name: datadir-service-name-mongodb-2
  labels:
    ordinal: "2"
    projectName: "project-name"
    serviceName: "service-name"
    dbType: "mongodb"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      capacity: "1Gi"
      ordinal: "2"
      projectName: "project-name"
      serviceName: "service-name"
      dbType: "mongodb"