apiVersion: v1
kind: Service
metadata:
  name: mongo-exposer-0
  namespace: mongodb
spec:
  ports:
  - nodePort: 32000
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    exposed-name: mongo-0
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-exposer-1
  namespace: mongodb
spec:
  ports:
  - nodePort: 32001
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    exposed-name: mongo-1
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-exposer-2
  namespace: mongodb
spec:
  ports:
  - nodePort: 32002
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    exposed-name: mongo-2
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
