apiVersion: v1
kind: Secret
metadata:
  namespace: project-name
  name: service-name-mongodb
  labels:
    projectName: "project-name" 
    serviceName: "service-name"
    dbType: "mongodb"
type: Opaque
data:
  keyfile: MWYyZDFlMmU2N2Rm