apiVersion: v1
kind: Service
metadata:
  name: service-name-mongodb-sts
  namespace: project-name
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    projectName: "project-name"
    serviceName: "service-name"
    dbType: "mongodb"
spec:
  ports:
    - protocol: "TCP"
      port: 27017
      targetPort: 27017
  selector:
    projectName: "project-name"
    serviceName: "service-name"
    dbType: "mongodb"
  clusterIP: "None"
