apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: mongodb
  name: mongo-cloud-infra-sa
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: mongodb
  name: mongo-cloud-infra-patcher-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  namespace: mongodb
  name: mongo-cloud-infra-sa
