kind: PersistentVolume
apiVersion: v1
metadata:
  name: project-name--service-name-mongodb-0
  labels:
    ordinal: "0"
    projectName: "project-name"
    serviceName: "service-name"
    dbType: "mongodb"
    capacity: "1Gi"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/mongo-dir-0"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: project-name--service-name-mongodb-1
  labels:
    ordinal: "1"
    projectName: "project-name"
    serviceName: "service-name"
    dbType: "mongodb"
    capacity: "1Gi"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/mongo-dir-1"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: project-name--service-name-mongodb-2
  labels:
    ordinal: "2"
    projectName: "project-name"
    serviceName: "service-name"
    dbType: "mongodb"
    capacity: "1Gi"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/mongo-dir-2"