apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: mongodb
  name: mongo
spec:
  serviceName: "mongo-service"
  replicas: 3
  template:
    metadata:
      labels:
        role: mongo
    spec:
      serviceAccountName: mongo
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--smallfiles"
            - "--noprealloc"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
        - name: mongo-sidecar
          image: cvallance/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "role=mongo"
            - name: KUBERNETES_MONGO_SERVICE_NAME
              value: "mongo-service"
            - name: KUBE_NAMESPACE
              value: "mongodb"
            - name: KUBERNETES_CLUSTER_DOMAIN
              value: "cluster.local"
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
    spec:
      storageClassName: "mongo-pvdb"
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi