# MongoDb
---
apiVersion: v1
kind: Service
metadata:
  namespace: mongodb
  name: mongo-sts-service
  labels:
    name: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongo
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: mongodb
  name: mongo-sts
spec:
  serviceName: "mongo-sts-service"
  replicas: 1
  template:
    metadata:
      labels:
        role: mongo
    spec:
      serviceAccountName: mongo-cloud-infra-sa
      automountServiceAccountToken: true
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: smchin/mongo:3.4.9
          # imagePullPolicy: Always
          ports:
            - containerPort: 27017
          # resources:
          #   requests:
          #     memory: "16Gi"
          #     cpu: "4"
          #   limits:
          #     memory: "32Gi"
          #     cpu: "8"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "root"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "rootp@ssword"
            - name: IDENTITY_LABEL
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ENTRYPOINT_ARGS
              value: "--config /mnt/config/mongo.conf"
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 15
            timeoutSeconds: 1
          volumeMounts:
            - name: datadir
              mountPath: /data/db
            - name: mongo-keyfile
              mountPath: /mnt/keyfile
            - name: mongo-conf
              mountPath: /mnt/config
        - name: sidecar
          image: smchin/k8s-mongo-sidecar:0.1
          imagePullPolicy: Always
          env:
            - name: CLUSTER_EXTERNAL_IP
              value: "10.0.2.15"
            - name: MONGO_NODEPORT_SERVICE_LABLES
              value: "name=mongo-nodeport-service"
            - name: MONGODB_USERNAME
              value: "root"
            - name: MONGODB_PASSWORD
              value: "rootp@ssword"
            - name: MONGODB_DATABASE
              value: "admin"
            - name: MONGO_SIDECAR_POD_LABELS
              value: "role=mongo"
            - name: KUBERNETES_MONGO_SERVICE_NAME
              value: "mongo-sts-service"
            - name: KUBE_NAMESPACE
              value: mongodb
            - name: KUBERNETES_CLUSTER_DOMAIN
              value: "cluster.local"
      volumes:
        - name: mongo-keyfile
          configMap:
            name: mongo-keyfile
        - name: mongo-conf
          configMap:
            name: mongo-conf
        - name: config
          emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      namespace: mongodb
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
