# mongodb-pv2.yaml

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pvdb2
  labels:
    type: local
spec:
  storageClassName: mongo-pvdb
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/data/mongo-db2"